---
- name: Podman may need ip_tables kernel modules
  ansible.builtin.command: modprobe ip_tables
  become: true

- name: Check if git, buildah and podman are installed
  ansible.builtin.package_facts:
    manager: "auto"
  # This is noisy and otherwise sensitive to print
  no_log: true

- name: Retrieve list of missing required packages
  ansible.builtin.set_fact:
    _missing_packages: "{{ images_packages | difference(ansible_facts['packages'].keys()) }}"

# This allows us to avoid needlessly escalating privileges if the packages are already installed
# (this role can otherwise run entirely unprivileged)
- when: _missing_packages | length > 0
  block:
    - name: Install required packages
      become: true
      ansible.builtin.package:
        name: "{{ images_packages }}"
        state: present
  rescue:
    - name: Fail due to missing packages
      ansible.builtin.fail:
        msg: |
          Failed to elevate privileges and install missing required packages.
          Install the following packages before running this role again:
          {{ _missing_packages | join(' ') }}
