images_ansible_name: ansible-core
images_ansible_version: latest

images_available:
  # TODO: re-enable arch
  # - name: localhost/test-image
  #   tag: archlinux
  #   script: ansible-test/archlinux/build.sh
  #   pythons:
  #     - "3.10"
  - name: localhost/test-image
    tag: centos-stream8
    script: ansible-test/centos-stream8/build.sh
    pythons:
      - "3.6"
      - "3.8"
      - "3.9"
  - name: localhost/test-image
    tag: debian-bullseye
    script: ansible-test/debian-bullseye/build.sh
    pythons:
      - "3.9"

# Whether to always build the image (even if it already exists)
images_build: true

# Whether to test the images or not
images_test: true

# Whether ara should be enabled and configured to record playbook results on an ara server
images_enable_ara: false
# Note: If running the ara server locally, this would be your interface IP (not 127.0.0.1 which is the container itself)
#       Your will need to add your interface IP in ARA_ALLOWED_HOSTS or in the server's settings.yaml
images_ara_api_server: "http://{{ ansible_default_ipv4['address'] }}:8000"
# images_ara_api_username:
# images_ara_api_password:

images_packages:
  - git
  - buildah
  - podman

images_venv: "{{ ansible_user_dir }}/.ansible/tmp/community_images_venv"
images_venv_cleanup: true
